name: impact-dashboard
channels:
  - conda-forge
 # - defaults
dependencies:
  - python=3.9
  - plotly
  - pandas
  - dash
  - openpmd-beamphysics =0.5.6
  - dash-bootstrap-components
  - flask-caching
  - pymongo
  - pip
  - pip:
    - dash-defer-js-import