name: impact-dashboard
channels:
  - conda-forge
 # - defaults
dependencies:
  - python=3.9
  - plotly
  - pandas
  - dash =2.0.0
  - openpmd-beamphysics =0.5.7
  - dash-bootstrap-components =0.13
  - flask-caching
  - pymongo
  - pip
  - pip:
    - dash-defer-js-import